# Generated by Django 4.0.4 on 2022-06-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('tipo', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
