# Generated by Django 4.0.4 on 2022-05-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('imagemtipo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('nome', models.TextField(max_length=255)),
                ('numero', models.IntegerField()),
                ('habilidade', models.TextField(max_length=255)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('descricao', models.TextField(max_length=255)),
                ('shinyimg', models.ImageField(upload_to='')),
                ('tipos', models.ManyToManyField(to='pokedex.tipopokemon')),
            ],
        ),
    ]
